### ISSUE TITLE
why are bash snippets still shown?

### ISSUE THREAD

**Issue by nhooyr** [Phidica/sublime-fish#17]
E.g. 
<img width="750" alt="screen shot 2018-07-15 at 8 28 21 am" src="https://user-images.githubusercontent.com/10180857/42733951-0c83c55c-8809-11e8-9363-7d94f2bad3f7.png">

The first is the bash `if` statement snippet but the second is the fish one.

Any ideas on how to disable the bash one?

**Comment by nhooyr** [comment]
Ah, this makes sense. Its due to #18

**Comment by nhooyr** [comment]
I'll open an issue upstream.

**Comment by nhooyr** [comment]
See https://github.com/sublimehq/Packages/pull/1664

**Comment by Phidica** [comment]
I already opened an issue for this, just before you did because I noticed it and got fed up with it at the same time :^) sublimehq/Packages#1663. It isn't because of #18, but because of the scope in the snippets files. So a separate pull would be required for changing the snippets. I think it should be coordinated in and referenced to the issue I opened, as yes it is an upstream matter.

**Comment by Phidica** [comment]
This is now solved upstream by sublimehq/Packages#1923.
