### ISSUE TITLE
Include by default in sublime text

### ISSUE THREAD

**Issue by nhooyr** [Phidica/sublime-fish#19]
Would be awesome to see this package included by default in sublime text.

**Comment by nhooyr** [comment]
This unfortunately cannot happen at the moment.

See https://github.com/sublimehq/Packages/tree/289782ff2e4cb58de171579c7fc86fe00d280619#new-packages

**Comment by rwols** [comment]
There is also the issue that the syntax file should be based on the more modern .sublime-syntax format.

**Comment by Phidica** [comment]
I agree converting to .sublime-syntax is important. Hopefully, by the time we have that then submission of new packages to sublimehq will be open

**Comment by issmirnov** [comment]
What are the main barriers to convert to `sublime-syntax`? Can this be automated at all, or is this a painstaking process by hand?

**Comment by Phidica** [comment]
I believe there is a conversion process available, however I'm cautious of the extent to which it fully applies the improved technical abilities of the `sublime-syntax` format (intelligent popping of scopes and so on). So I have been expecting that I'll need to rewrite from the ground up just to ensure that it's working as efficiently as possible. Since submission of new packages to the default set is still closed (and I can't find an issue which seems to be tracking progress on getting it open again), it has been low on my priorities list to start work on this.

**Comment by Phidica** [comment]
@issmirnov do you have another use case which calls for the syntax to be in `sublime-syntax` format rather than `tmLanguage`?

**Comment by issmirnov** [comment]
@Phidica thanks for the info. The reason I ask is that I'm a frequent user of [sharkpd/bat](https://github.com/sharkdp/bat), which [uses](https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions) `sublime-syntax` files for the [highlighting engine](https://github.com/trishume/syntect/). 

I'm planning on getting more into fish scripts, so was trying to find a way to convert the `tmLanguage` from this repo into the `sublime-syntax` format. Installed SL3, but it seems to be converting to `YAML-tmLanguage`.

Since this would require a rewrite from the ground up I am in no way asking you to make this your top priority 😄

**Comment by Phidica** [comment]
I know it doesn't solve your problem exactly, but as one workaround I might suggest looking at `fish_indent` (it comes with `fish`), which can read fish scripts from standard input and print them, formatted, to standard output. Try `cat <script> | fish_indent --ansi` to colourise the output.

I've done a little more testing now and found that converting `tmLanguage` to `sublime-syntax` can be done with ST alone, by opening `fish.tmLanguage` and selecting *Tools > Developer > New syntax from fish.tmLanguage...* However, it doesn't work on `fish.tmLanguage` right now because of errors in parsing some comments in the file. I'm going to push a fix for that issue, though I won't tag the release so you'll have to download the file manually. After that, you should be able to run the conversion to create a `sublime-syntax` for your own use.

**Comment by issmirnov** [comment]
@Phidica thank you so much! I didn't know about `fish_indent`, and with your changes to the comments file I was able to get the `sublime-syntax` file generated and working with bat. Very much appreciate the input and advice!

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by Phidica** [comment]
Fine by me. With this package now containing a few advanced plugins, it might be out of scope for inclusion in the default set anyway.

It seems submission of new packages to ST is gonna keep being blocked for a while yet. We can review again in the future when that becomes possible, if needed.
