### ISSUE TITLE
Language name eats too much space in the status bar

### ISSUE THREAD

**Issue by andreiborisov** [Phidica/sublime-fish#24]
I wonder if it's possible to change the displayed name of the fish language in Sublime status bar to simply `fish`. Right now it's way too long and eats a lot of space in the status bar:

<img width="478" alt="CleanShot 2020-06-11 at 11 38 24@2x" src="https://user-images.githubusercontent.com/13354491/84364008-32b17e00-abd8-11ea-974a-a7b9e8f91ba9.png">

**Comment by Phidica** [comment]
The syntax name is controlled by line 4 of the `fish.sublime-syntax` file. If it is important for your purposes that it be shorter, then you could do a manual install of the package following the instructions in the README and modify the syntax to choose a shorter name. I don't believe this should cause anything to break, you'd just have to watch out for new releases and periodically update then modify the name again. 

I'm not aware of any other way to control the apparent name of the syntax used in that part of the status bar.

I would prefer not to change the as-distributed name of the syntax to anything else, because currently it mirrors the style of the default bash syntax, which is `Bourne Again Shell (bash)`.

**Comment by andreiborisov** [comment]
Thank you for the suggestion!

That absolutely makes sense, I wasn’t aware that Bash syntax has the same naming format.

I’ve reported it in the bundled packages repo (https://github.com/sublimehq/Packages/issues/2384), perhaps they are willing to change it in the Bash syntax package.

**Comment by andreiborisov** [comment]
Bash syntax name is changed to ”Bash” upstream: https://github.com/sublimehq/Packages/issues/2384

**Comment by Phidica** [comment]
Next release will contain this change. Follow instructions in the README for a local install if you'd like to get it sooner, noting the change is currently on the `devel` branch. Closing for now.
