### ISSUE TITLE
Make the base scope `source.shell.fish`, in order to get the new shell build system to work with it

### ISSUE THREAD

**Issue by rwols** [Phidica/sublime-fish#9]
If the base scope is `source.shell.fish`, the `ShellScript.sublime-build` can pick it up and then we can run our fish scripts from within sublime with <kbd>cmd</kbd><kbd>B</kbd>.

**Comment by Phidica** [comment]
I'm not sure I understand you. Are you saying that the base scope should be made this? Because [it already is](https://github.com/Phidica/sublime-fish-shell-improved/blob/13ac9efcd2c7e42f10a31f4b9f8c6f153c2c4484/fish.YAML-tmLanguage#L3) (since 79802e6). That being said, wouldn't it make more sense for this package to provide its own version of `sublime-build` rather than depend on `ShellScript` to provide it? I would be happy to include a build system with the package

**Comment by rwols** [comment]
You're totally right, I haven't pulled from the master branch in a while.

> That being said, wouldn't it make more sense for this package to provide its own version of sublime-build rather than depend on ShellScript to provide it?

I specifically made that build system so that it would also work with zsh, tcsh, fish, etc.
